"""Situation report generator — full Markdown report from an assessment.

Runs AFTER the coordinator's rule-based decision. Every figure comes
straight from the assessment dict; nothing here is generated by an LLM
(the optional LLM-drafted warning_text is included verbatim, clearly
labelled). Reports are saved to data/reports/ with a UTC timestamp.
"""

import datetime as dt
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = PROJECT_ROOT / "data" / "reports"


def _fmt(value, unit=""):
    if value is None:
        return "n/a"
    if isinstance(value, (int, float)) and abs(value) >= 1000:
        return f"{value:,.0f}{unit}"
    return f"{value}{unit}"


def build_report(assessment: dict) -> str:
    now = dt.datetime.now(dt.timezone.utc)
    a = assessment
    aoi_name = a.get("aoi", {}).get("name")
    if not aoi_name:
        try:
            from agents.basins import get_basin

            aoi_name = get_basin(a["basin"])["name"] + " basin"
        except Exception:  # noqa: BLE001 — report must build even for unknown AOIs
            aoi_name = str(a.get("basin", "unknown")).title()
    lines = [
        "# NDMA Flood Early Warning — Situation Report",
        "",
        f"**Area:** {aoi_name} | **Generated:** {now:%Y-%m-%d %H:%M} UTC | "
        "**System:** multi-agent prototype (automated)",
        "",
        "## 1. Assessment",
        "",
        f"| Risk score | Risk level | Decision |",
        f"|---|---|---|",
        f"| **{_fmt(a['risk_score'])}/100** | **{a['risk_level'].upper()}** | "
        f"**{a['decision']['action'].replace('_', ' ')}** |",
        "",
        f"Recommended action: {a['decision']['description']}",
        "",
    ]
    if a.get("degraded"):
        lines += [
            f"> **DEGRADED ASSESSMENT** — failed agents: "
            f"{', '.join(a['failed_agents'])}. Weights renormalised over "
            "the remaining components.",
            "",
        ]
    if a.get("warning_text"):
        lines += ["### Draft public warning", "", f"> {a['warning_text']}", ""]

    comp = a["components"]
    lines += [
        "## 2. Risk components",
        "",
        "| Component | Score (0-100) | Weight |",
        "|---|---|---|",
        f"| River discharge (GloFAS) | {_fmt(comp['river'])} | {a['weights']['river']} |",
        f"| Forecast rain 72h (GFS) | {_fmt(comp['rain_forecast'])} | {a['weights']['rain_forecast']} |",
        f"| Observed rain 72h (GPM) | {_fmt(comp['rain_observed'])} | {a['weights']['rain_observed']} |",
        "",
    ]

    river = a["agents"].get("river", {})
    lines += ["## 3. River situation (GloFAS forecast)", ""]
    if river.get("status") == "ok":
        leadtimes = ", ".join(str(h) + "h" for h in river.get("leadtime_hours", []))
        lines += [
            f"Forecast issued: {river.get('forecast_date', 'n/a')} | "
            f"leadtimes: {leadtimes or 'n/a'}",
            "",
            "| Station | Peak forecast (m³/s) | Peak (cusecs) | FFD category |",
            "|---|---|---|---|",
        ]
        for name, s in river.get("stations", {}).items():
            cusecs = round(s["peak_m3s"] / 0.0283168)
            lines.append(
                f"| {name} | {_fmt(s['peak_m3s'])} | {_fmt(cusecs)} | "
                f"{s['flood_category'].replace('_', ' ')} |"
            )
        lines.append("")
    else:
        lines += [f"River agent unavailable: {river.get('error', 'unknown')}", ""]

    weather = a["agents"].get("weather", {})
    lines += ["## 4. Rainfall", ""]
    if weather.get("status") == "ok":
        obs, fcst = weather["observed_rain_mm"], weather["forecast_rain_mm"]
        lines += [
            "| Window | Basin mean (mm) | Basin max (mm) |",
            "|---|---|---|",
            f"| Observed last 24h | {_fmt(obs['last_24h']['basin_mean'])} | {_fmt(obs['last_24h']['basin_max'])} |",
            f"| Observed last 72h | {_fmt(obs['last_72h']['basin_mean'])} | {_fmt(obs['last_72h']['basin_max'])} |",
            f"| Forecast next 72h | {_fmt(fcst['next_72h']['basin_mean'])} | {_fmt(fcst['next_72h']['basin_max'])} |",
            "",
            f"Observed data latency: {weather['observed_latency_hours']} h "
            f"(window ends {weather['observed_window_end_utc']}).",
            "",
        ]
    else:
        lines += [f"Weather agent unavailable: {weather.get('error', 'unknown')}", ""]

    pop = a["agents"].get("population", {})
    terrain = a["agents"].get("terrain", {})
    lines += ["## 5. Exposure", ""]
    if pop.get("status") == "ok":
        lines += [
            f"- Population in area (WorldPop {pop['year']}): "
            f"**{_fmt(pop['total_population'])}**",
            f"- On floodplain ({pop['floodplain_definition']}): "
            f"**{_fmt(pop['floodplain_population'])}**",
        ]
    if terrain.get("status") == "ok":
        lines.append(f"- Area: {_fmt(terrain['basin_area_km2'], ' km²')}")
    lines += [
        "",
        "## 6. Caveats",
        "",
        "- Automated prototype on open data — verify against FFD/PMD "
        "bulletins before operational use.",
        "- GloFAS covers major-river discharge only: no flash floods, "
        "coastal flooding, or inundation extent.",
        "- Floodplain population uses a slope < 2° proxy, not mapped "
        "inundation.",
    ]
    if a.get("aoi", {}).get("kind", "basin") == "basin":
        lines.append(
            "- Basin polygon (HydroBASINS level 6) is ~30% larger than "
            "the true catchment.")
    lines += [
        "- GloFAS discharge runs ~2x low vs FFD-reported flows at these "
        "stations (2010/2022 backtest), so river flood categories are "
        "conservative — treat any category above normal seriously.",
        "",
        "*Sources: GloFAS (Copernicus EWDS), GPM IMERG, NOAA GFS, SRTM, "
        "HydroSHEDS, WorldPop.*",
    ]
    return "\n".join(lines)


def save_report(assessment: dict) -> str:
    """Persist a report locally in TWO formats side by side:
      - Markdown (human-readable situation report)
      - JSON (the full assessment dict — every number, agent output and
        conversation message, so any figure in the Markdown can be
        traced back to raw agent output)
    Filename carries the AOI slug + UTC timestamp to the second, so a
    history of runs accumulates in data/reports/ and nothing is ever
    overwritten. Returns the Markdown path (JSON sits beside it)."""
    import json

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    basin = assessment.get("basin", "basin")
    stem = f"sitrep_{basin}_{dt.datetime.now(dt.timezone.utc):%Y%m%d_%H%M%S}"
    md_path = REPORTS_DIR / f"{stem}.md"
    md_path.write_text(build_report(assessment), encoding="utf-8")
    (REPORTS_DIR / f"{stem}.json").write_text(
        json.dumps(assessment, indent=2, default=str), encoding="utf-8"
    )
    return str(md_path)


def list_reports() -> list[dict]:
    """Saved-report history, newest first."""
    items = []
    for p in sorted(REPORTS_DIR.glob("sitrep_*.md"),
                    key=lambda p: p.stat().st_mtime, reverse=True):
        items.append({
            "name": p.name,
            "json_name": p.with_suffix(".json").name
            if p.with_suffix(".json").exists() else None,
            "size_kb": round(p.stat().st_size / 1024, 1),
            "modified_utc": dt.datetime.fromtimestamp(
                p.stat().st_mtime, dt.timezone.utc
            ).isoformat(timespec="seconds"),
        })
    return items
